CREATE SEQUENCE IF NOT EXISTS currency_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE currency
(
    id     INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    symbol VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_currency PRIMARY KEY (id)
);

ALTER TABLE currency
    ADD CONSTRAINT uc_currency_symbol UNIQUE (symbol);